#!/usr/bin/env node
// Runs before `npm publish`: the package must be built from the release
// commit, so what npm serves matches the `v<version>` tag. The tag sits on a
// commit that adds the built dist/ for the GitHub Action; its parent is the
// release commit on main. Either one is fine.
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';

const git = (...args) => {
  try {
    return execFileSync('git', args, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
};

const { version } = JSON.parse(
  readFileSync(new URL('../package.json', import.meta.url), 'utf8'),
);
const tag = `v${version}`;
const tagged = git('rev-parse', '--verify', '--quiet', `${tag}^{commit}`);
const release = tagged && git('rev-parse', '--verify', '--quiet', `${tag}^`);
const head = git('rev-parse', 'HEAD');
// Built files are regenerated by the build; anything else must be committed.
const changed = git('status', '--porcelain', '--untracked-files=no')
  .split('\n')
  .filter((line) => line && !/^.. dist\//.test(line));

const problems = [];
if (!tagged) problems.push(`tag ${tag} does not exist`);
else if (head !== tagged && head !== release) {
  problems.push(
    `HEAD is not ${tag} (check out main at the release commit or the tag)`,
  );
}
if (changed.length > 0)
  problems.push(`uncommitted changes:\n  ${changed.join('\n  ')}`);

if (problems.length > 0) {
  console.error(`Refusing to publish ${version}:\n- ${problems.join('\n- ')}`);
  process.exit(1);
}
